DELETE FROM Object_Metadata_Join;
DELETE FROM File;
DELETE FROM Object_Object_Join;
DELETE FROM Object_Folder_Join;
DELETE FROM Metadata;
DELETE FROM Format;
DELETE FROM Folder_User_Join;
DELETE FROM Folder_Group_Join;
DELETE FROM AccessPoint_Object_Join;
DELETE FROM Object;
DELETE FROM MetadataSchema_User_Join;
DELETE FROM MetadataSchema_Group_Join;
DELETE FROM FormatCategory;
DELETE FROM Folder;
DELETE FROM AccessProvider;
DELETE FROM AccessPoint_User_Join;
DELETE FROM AccessPoint_Group_Join;
DELETE FROM Version;
DELETE FROM ObjectType;
DELETE FROM ObjectRelationType;
DELETE FROM ObjectFolderType;
DELETE FROM MetadataSchema;
DELETE FROM Language;
DELETE FROM FormatType;
DELETE FROM FolderType;
DELETE FROM Destination;
DELETE FROM AccessPoint;


INSERT INTO Version(Major, Minor, `Release`, ScriptName, DateCreated)VALUES('06','00','0000','initial', NOW());
INSERT INTO FolderType( ID, Name, DateCreated ) VALUES( 1, 'Folder', NOW() );
INSERT INTO ObjectFolderType( ID, Name )VALUES( 1, 'Physical' );
INSERT INTO ObjectFolderType( ID, Name )VALUES( 2, 'Link' );
INSERT INTO Language( LanguageCode, Name ) VALUES( 'ar', 'Arabic' );
INSERT INTO Language( LanguageCode, Name ) VALUES( 'bg', 'Bulgarian' );
INSERT INTO Language( LanguageCode, Name ) VALUES( 'ca', 'Catalan' );
INSERT INTO Language( LanguageCode, Name ) VALUES( 'cz', 'Czech' );
INSERT INTO Language( LanguageCode, Name ) VALUES( 'da', 'Danish' );
INSERT INTO Language( LanguageCode, Name ) VALUES( 'de', 'German' );
INSERT INTO Language( LanguageCode, Name ) VALUES( 'de-ch', 'Swiss-German' );
INSERT INTO Language( LanguageCode, Name ) VALUES( 'el', 'Greek' );
INSERT INTO Language( LanguageCode, Name ) VALUES( 'en', 'English' );
INSERT INTO Language( LanguageCode, Name ) VALUES( 'es', 'Spanish' );
INSERT INTO Language( LanguageCode, Name ) VALUES( 'eu', 'Basque' );
INSERT INTO Language( LanguageCode, Name ) VALUES( 'fa', 'Persian' );
INSERT INTO Language( LanguageCode, Name ) VALUES( 'fi', 'Finish' );
INSERT INTO Language( LanguageCode, Name ) VALUES( 'fr', 'French' );
INSERT INTO Language( LanguageCode, Name ) VALUES( 'fr-be', 'French(Belgium)' );
INSERT INTO Language( LanguageCode, Name ) VALUES( 'fr-ch', 'French (Swiss)' );
INSERT INTO Language( LanguageCode, Name ) VALUES( 'fr-lu', 'French (Luxembourg)' );
INSERT INTO Language( LanguageCode, Name ) VALUES( 'ga', 'Irish' );
INSERT INTO Language( LanguageCode, Name ) VALUES( 'gl', 'Galician' );
INSERT INTO Language( LanguageCode, Name ) VALUES( 'hi', 'Hindi' );
INSERT INTO Language( LanguageCode, Name ) VALUES( 'hu', 'Hungarian' );
INSERT INTO Language( LanguageCode, Name ) VALUES( 'hy', 'Armenian' );
INSERT INTO Language( LanguageCode, Name ) VALUES( 'id', 'Indonesian' );
INSERT INTO Language( LanguageCode, Name ) VALUES( 'it', 'Italian' );
INSERT INTO Language( LanguageCode, Name ) VALUES( 'ja', 'Japanese' );
INSERT INTO Language( LanguageCode, Name ) VALUES( 'lv', 'Latvian' );
INSERT INTO Language( LanguageCode, Name ) VALUES( 'nl', 'Dutch' );
INSERT INTO Language( LanguageCode, Name ) VALUES( 'nl-be', 'Dutch (Belgium)' );
INSERT INTO Language( LanguageCode, Name ) VALUES( 'no', 'Norwegian' );
INSERT INTO Language( LanguageCode, Name ) VALUES( 'pl', 'Polish' );
INSERT INTO Language( LanguageCode, Name ) VALUES( 'pt', 'Portoguese' );
INSERT INTO Language( LanguageCode, Name ) VALUES( 'ro', 'Romanian' );
INSERT INTO Language( LanguageCode, Name ) VALUES( 'ru', 'Russian' );
INSERT INTO Language( LanguageCode, Name ) VALUES( 'sl', 'Slovenian' );
INSERT INTO Language( LanguageCode, Name ) VALUES( 'sv', 'Swedish' );
INSERT INTO Language( LanguageCode, Name ) VALUES( 'th', 'Thai' );
INSERT INTO Language( LanguageCode, Name ) VALUES( 'tr', 'Turkish' );