CREATE TABLE `Project` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `Name` VARCHAR(255) NOT NULL COMMENT '',
  `DateCreated` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`Id`)  COMMENT '',
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC)  COMMENT '');
