ALTER TABLE `Metadata` 
CHANGE COLUMN `MetadataXML` `MetadataXML` LONGTEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL ;

ALTER TABLE `Metadata` 
DROP PRIMARY KEY,
ADD PRIMARY KEY (`GUID`);
