<?xml version="1.0" encoding="utf-8"?><Database Name="MCM" Class="MCMDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.56.101;Initial Catalog=MCM;Persist Security Info=True;User ID=sa" SettingsObjectName="Geckon.MCM.Data.Linq.Properties.Settings" SettingsPropertyName="MCMConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AccessPoint" Member="AccessPoints">
    <Type Name="AccessPoint">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="SubscriptionGUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="AccessPoint_AccessPoint_Group_Join" Member="AccessPoint_Group_Joins" ThisKey="ID" OtherKey="AcessPointID" Type="AccessPoint_Group_Join" />
      <Association Name="AccessPoint_AccessPoint_Object_Join" Member="AccessPoint_Object_Joins" ThisKey="ID" OtherKey="AccessPointID" Type="AccessPoint_Object_Join" />
      <Association Name="AccessPoint_AccessPoint_User_Join" Member="AccessPoint_User_Joins" ThisKey="ID" OtherKey="AccessPointID" Type="AccessPoint_User_Join" />
      <Association Name="Conversion_AccessPoint" Member="Conversion" ThisKey="ID" OtherKey="ID" Type="Conversion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ObjectType" Member="ObjectTypes">
    <Type Name="ObjectType" Id="ID1">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="ObjectType_Object" Member="Objects" ThisKey="ID" OtherKey="ObjectTypeID" Type="Object" />
    </Type>
  </Table>
  <Table Name="dbo.AccessPoint_Group_Join" Member="AccessPoint_Group_Joins">
    <Type Name="AccessPoint_Group_Join">
      <Column Name="AcessPointID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GroupGUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Permission" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Association Name="AccessPoint_AccessPoint_Group_Join" Member="AccessPoint" ThisKey="AcessPointID" OtherKey="ID" Type="AccessPoint" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AccessPoint_Object_Join" Member="AccessPoint_Object_Joins">
    <Type Name="AccessPoint_Object_Join">
      <Column Name="AccessPointID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ObjectID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateModified" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="AccessPoint_AccessPoint_Object_Join" Member="AccessPoint" ThisKey="AccessPointID" OtherKey="ID" Type="AccessPoint" IsForeignKey="true" />
      <Association Name="Object_AccessPoint_Object_Join" Member="Object" ThisKey="ObjectID" OtherKey="ID" Type="Object" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AccessPoint_User_Join" Member="AccessPoint_User_Joins">
    <Type Name="AccessPoint_User_Join">
      <Column Name="AccessPointID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserGUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Permission" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Association Name="AccessPoint_AccessPoint_User_Join" Member="AccessPoint" ThisKey="AccessPointID" OtherKey="ID" Type="AccessPoint" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AccessProvider" Member="AccessProviders">
    <Type Name="AccessProvider">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DestinationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BasePath" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="StringFormat" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Association Name="Destination_AccessProvider" Member="Destination" ThisKey="DestinationID" OtherKey="ID" Type="Destination" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Conversion" Member="Conversions">
    <Type Name="Conversion">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AccessPointID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FormatCategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FormatID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DestinationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Association Name="Conversion_AccessPoint" Member="AccessPoint" ThisKey="ID" OtherKey="ID" Type="AccessPoint" Cardinality="One" />
      <Association Name="Destination_Conversion" Member="Destination" ThisKey="DestinationID" OtherKey="ID" Type="Destination" IsForeignKey="true" />
      <Association Name="Format_Conversion" Member="Format" ThisKey="FormatID" OtherKey="ID" Type="Format" IsForeignKey="true" />
      <Association Name="FormatCategory_Conversion" Member="FormatCategory" ThisKey="FormatCategoryID" OtherKey="ID" Type="FormatCategory" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Destination" Member="Destinations">
    <Type Name="Destination">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SubscriptionGUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Association Name="Destination_AccessProvider" Member="AccessProviders" ThisKey="ID" OtherKey="DestinationID" Type="AccessProvider" />
      <Association Name="Destination_Conversion" Member="Conversions" ThisKey="ID" OtherKey="DestinationID" Type="Conversion" />
      <Association Name="Destination_File" Member="Files" ThisKey="ID" OtherKey="DestinationID" Type="File" />
    </Type>
  </Table>
  <Table Name="dbo.[File]" Member="Files">
    <Type Name="File">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ObjectID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FormatID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DestinationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Filename" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="OriginalFilename" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="FolderPath" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Association Name="File_File" Member="Files" ThisKey="ID" OtherKey="ParentID" Type="File" />
      <Association Name="Destination_File" Member="Destination" ThisKey="DestinationID" OtherKey="ID" Type="Destination" IsForeignKey="true" />
      <Association Name="File_File" Member="File1" ThisKey="ParentID" OtherKey="ID" Type="File" IsForeignKey="true" />
      <Association Name="Format_File" Member="Format" ThisKey="FormatID" OtherKey="ID" Type="Format" IsForeignKey="true" />
      <Association Name="Object_File" Member="Object" ThisKey="ObjectID" OtherKey="ID" Type="Object" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Folder_Group_Join" Member="Folder_Group_Joins">
    <Type Name="Folder_Group_Join">
      <Column Name="FolderID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GroupGUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Permission" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Association Name="Folder_Folder_Group_Join" Member="Folder" ThisKey="FolderID" OtherKey="ID" Type="Folder" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Folder_User_Join" Member="Folder_User_Joins">
    <Type Name="Folder_User_Join">
      <Column Name="FolderID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserGUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Permission" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Association Name="Folder_Folder_User_Join" Member="Folder" ThisKey="FolderID" OtherKey="ID" Type="Folder" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FolderType" Member="FolderTypes">
    <Type Name="FolderType" Id="ID4">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="FolderType_Folder" Member="Folders" ThisKey="ID" OtherKey="FolderTypeID" Type="Folder" />
    </Type>
  </Table>
  <Table Name="dbo.Format" Member="Formats">
    <Type Name="Format">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FormatCategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="FormatXml" Type="System.Xml.Linq.XElement" DbType="Xml" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="MimeType" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="FileExtension" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="Format_Conversion" Member="Conversions" ThisKey="ID" OtherKey="FormatID" Type="Conversion" />
      <Association Name="Format_File" Member="Files" ThisKey="ID" OtherKey="FormatID" Type="File" />
      <Association Name="FormatCategory_Format" Member="FormatCategory" ThisKey="FormatCategoryID" OtherKey="ID" Type="FormatCategory" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FormatCategory" Member="FormatCategories">
    <Type Name="FormatCategory">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FormatTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="FormatCategory_Conversion" Member="Conversions" ThisKey="ID" OtherKey="FormatCategoryID" Type="Conversion" />
      <Association Name="FormatCategory_Format" Member="Formats" ThisKey="ID" OtherKey="FormatCategoryID" Type="Format" />
      <Association Name="FormatType_FormatCategory" Member="FormatType" ThisKey="FormatTypeID" OtherKey="ID" Type="FormatType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FormatType" Member="FormatTypes">
    <Type Name="FormatType" Id="ID5">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="FormatType_FormatCategory" Member="FormatCategories" ThisKey="ID" OtherKey="FormatTypeID" Type="FormatCategory" />
    </Type>
  </Table>
  <Table Name="dbo.Language" Member="Languages">
    <Type Name="Language" Id="ID2">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="LanguageCode" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CountryName" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="Language_Metadata" Member="Metadatas" ThisKey="ID" OtherKey="LanguageID" Type="Metadata" />
    </Type>
  </Table>
  <Table Name="dbo.Metadata" Member="Metadatas">
    <Type Name="Metadata">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ObjectID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LanguageID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MetadataSchemaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MetadataXml" Type="System.Xml.Linq.XElement" DbType="Xml NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateModified" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateLocked" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LockUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Language_Metadata" Member="Language" ThisKey="LanguageID" OtherKey="ID" Type="Language" IsForeignKey="true" />
      <Association Name="MetadataSchema_Metadata" Member="MetadataSchema" ThisKey="MetadataSchemaID" OtherKey="ID" Type="MetadataSchema" IsForeignKey="true" />
      <Association Name="Object_Metadata" Member="Object" ThisKey="ObjectID" OtherKey="ID" Type="Object" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MetadataSchema" Member="MetadataSchemas">
    <Type Name="MetadataSchema">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="SchemaXml" Type="System.Xml.Linq.XElement" DbType="Xml NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="MetadataSchema_Metadata" Member="Metadatas" ThisKey="ID" OtherKey="MetadataSchemaID" Type="Metadata" />
      <Association Name="MetadataSchema_MetadataSchema_Group_Join" Member="MetadataSchema_Group_Joins" ThisKey="ID" OtherKey="MetadataSchemaID" Type="MetadataSchema_Group_Join" />
      <Association Name="MetadataSchema_MetadataSchema_User_Join" Member="MetadataSchema_User_Joins" ThisKey="ID" OtherKey="MetadataSchemaID" Type="MetadataSchema_User_Join" />
    </Type>
  </Table>
  <Table Name="dbo.MetadataSchema_Group_Join" Member="MetadataSchema_Group_Joins">
    <Type Name="MetadataSchema_Group_Join">
      <Column Name="MetadataSchemaID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GroupGUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Permission" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Association Name="MetadataSchema_MetadataSchema_Group_Join" Member="MetadataSchema" ThisKey="MetadataSchemaID" OtherKey="ID" Type="MetadataSchema" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MetadataSchema_User_Join" Member="MetadataSchema_User_Joins">
    <Type Name="MetadataSchema_User_Join">
      <Column Name="MetadataSchemaID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserGUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Permission" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Association Name="MetadataSchema_MetadataSchema_User_Join" Member="MetadataSchema" ThisKey="MetadataSchemaID" OtherKey="ID" Type="MetadataSchema" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Object" Member="Objects">
    <Type Name="Object">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ObjectTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Association Name="Object_AccessPoint_Object_Join" Member="AccessPoint_Object_Joins" ThisKey="ID" OtherKey="ObjectID" Type="AccessPoint_Object_Join" />
      <Association Name="Object_File" Member="Files" ThisKey="ID" OtherKey="ObjectID" Type="File" />
      <Association Name="Object_Metadata" Member="Metadatas" ThisKey="ID" OtherKey="ObjectID" Type="Metadata" />
      <Association Name="Object_Object_Folder_Join" Member="Object_Folder_Joins" ThisKey="ID" OtherKey="ObjectID" Type="Object_Folder_Join" />
      <Association Name="Object_Object_Object_Join" Member="Object_Object_Joins" ThisKey="ID" OtherKey="ObjectID1" Type="Object_Object_Join" />
      <Association Name="Object_Object_Object_Join1" Member="Object_Object_Joins1" ThisKey="ID" OtherKey="ObjectID2" Type="Object_Object_Join" />
      <Association Name="ObjectType_Object" Member="ObjectType" ThisKey="ObjectTypeID" OtherKey="ID" Type="ObjectType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Object_Folder_Join" Member="Object_Folder_Joins">
    <Type Name="Object_Folder_Join">
      <Column Name="ObjectID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FolderID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IsShortcut" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Association Name="Object_Object_Folder_Join" Member="Object" ThisKey="ObjectID" OtherKey="ID" Type="Object" IsForeignKey="true" />
      <Association Name="Folder_Object_Folder_Join" Member="Folder" ThisKey="FolderID" OtherKey="ID" Type="Folder" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Object_Object_Join" Member="Object_Object_Joins">
    <Type Name="Object_Object_Join">
      <Column Name="ObjectID1" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ObjectID2" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ObjectRelationTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Sequence" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Association Name="Object_Object_Object_Join" Member="Object" ThisKey="ObjectID1" OtherKey="ID" Type="Object" IsForeignKey="true" />
      <Association Name="Object_Object_Object_Join1" Member="Object1" ThisKey="ObjectID2" OtherKey="ID" Type="Object" IsForeignKey="true" />
      <Association Name="ObjectRelationType_Object_Object_Join" Member="ObjectRelationType" ThisKey="ObjectRelationTypeID" OtherKey="ID" Type="ObjectRelationType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ObjectRelationType" Member="ObjectRelationTypes">
    <Type Name="ObjectRelationType" Id="ID3">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="ObjectRelationType_Object_Object_Join" Member="Object_Object_Joins" ThisKey="ID" OtherKey="ObjectRelationTypeID" Type="Object_Object_Join" />
    </Type>
  </Table>
  <Table Name="dbo.Folder" Member="Folders">
    <Type Name="Folder">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FolderTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubscriptionGUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Association Name="Folder_Folder_Group_Join" Member="Folder_Group_Joins" ThisKey="ID" OtherKey="FolderID" Type="Folder_Group_Join" />
      <Association Name="Folder_Folder_User_Join" Member="Folder_User_Joins" ThisKey="ID" OtherKey="FolderID" Type="Folder_User_Join" />
      <Association Name="Folder_Object_Folder_Join" Member="Object_Folder_Joins" ThisKey="ID" OtherKey="FolderID" Type="Object_Folder_Join" />
      <Association Name="Folder_Folder" Member="Folders" ThisKey="ID" OtherKey="ParentID" Type="Folder" />
      <Association Name="Folder_Folder" Member="Folder1" ThisKey="ParentID" OtherKey="ID" Type="Folder" IsForeignKey="true" />
      <Association Name="FolderType_Folder" Member="FolderType" ThisKey="FolderTypeID" OtherKey="ID" Type="FolderType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FolderInfo" Member="FolderInfos">
    <Type Name="FolderInfo">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FolderTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubscriptionGUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="NumberOfSubFolders" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.PopulateDefaultData" Method="PopulateDefaultData">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ObjectType_Insert" Method="ObjectType_Insert">
    <Parameter Name="Value" Parameter="value" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="SystemPermission" Parameter="systemPermission" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ObjectType_Get" Method="ObjectType_Get">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="Value" Parameter="value" Type="System.String" DbType="VarChar(255)" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.ObjectType_Update" Method="ObjectType_Update">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="Value" Parameter="value" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="SystemPermission" Parameter="systemPermission" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ObjectType_Delete" Method="ObjectType_Delete">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="Value" Parameter="value" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="SystemPermission" Parameter="systemPermission" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Language_Get" Method="Language_Get">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="LanguageCode" Parameter="languageCode" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="CountryName" Parameter="countryName" Type="System.String" DbType="VarChar(255)" />
    <ElementType IdRef="ID2" />
  </Function>
  <Function Name="dbo.Language_Create" Method="Language_Create">
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="LanguageCode" Parameter="languageCode" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="CountryName" Parameter="countryName" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="SystemPermission" Parameter="systemPermission" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Language_Delete" Method="Language_Delete">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="SystemPermission" Parameter="systemPermission" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Language_Update" Method="Language_Update">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="LanguageCode" Parameter="languageCode" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="CountryName" Parameter="countryName" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="SystemPermission" Parameter="systemPermission" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ObjectRelationType_Get" Method="ObjectRelationType_Get">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="Value" Parameter="value" Type="System.String" DbType="VarChar(255)" />
    <ElementType IdRef="ID3" />
  </Function>
  <Function Name="dbo.ObjectRelationType_Create" Method="ObjectRelationType_Create">
    <Parameter Name="Value" Parameter="value" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="SystemPermission" Parameter="systemPermission" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ObjectRelationType_Delete" Method="ObjectRelationType_Delete">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="SystemPermission" Parameter="systemPermission" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ObjectRelationType_Update" Method="ObjectRelationType_Update">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="Value" Parameter="value" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="SystemPermission" Parameter="systemPermission" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.FolderType_Get" Method="FolderType_Get">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="VarChar(255)" />
    <ElementType IdRef="ID4" />
  </Function>
  <Function Name="dbo.FolderType_Delete" Method="FolderType_Delete">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="SystemPermission" Parameter="systemPermission" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.FolderType_Create" Method="FolderType_Create">
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="SystemPermission" Parameter="systemPermission" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.FolderType_Update" Method="FolderType_Update">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="SystemPermission" Parameter="systemPermission" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.FormatType_Create" Method="FormatType_Create">
    <Parameter Name="Value" Parameter="value" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="SystemPermission" Parameter="systemPermission" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.FormatType_Delete" Method="FormatType_Delete">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="SystemPermission" Parameter="systemPermission" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.FormatType_Update" Method="FormatType_Update">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="Value" Parameter="value" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="SystemPermission" Parameter="systemPermission" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.FormatType_Get" Method="FormatType_Get">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="Value" Parameter="value" Type="System.String" DbType="VarChar(255)" />
    <ElementType IdRef="ID5" />
  </Function>
</Database>